services:
  - type: web
    name: startup-act
    runtime: python
    repo: https://github.com/bennoomenfaker/vic-2026-startup-act
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python3 streamlit-app/server.py
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
